name: Build Sovereign Bark Server
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Upstream Tags
        run: |
          # Cette ligne magique aspire les vrais numéros de version du créateur
          git fetch --tags https://github.com/Finb/bark-server.git

      - name: Patch Source Code
        run: |
          # 1. Injection des IDs
          sed -i "s/topic[[:space:]]*=[[:space:]]*\"me.fin.bark\"/topic = \"${{ secrets.BUNDLE_ID }}\"/g" apns/apns.go
          sed -i "s/keyID[[:space:]]*=[[:space:]]*\"LH4T9V5U4R\"/keyID = \"${{ secrets.KEY_ID }}\"/g" apns/apns.go
          sed -i "s/teamID[[:space:]]*=[[:space:]]*\"5U8LBRXG3A\"/teamID = \"${{ secrets.TEAM_ID }}\"/g" apns/apns.go

          # 2. Remplacement chirurgical de la clé privée (sans toucher aux certificats Apple)
          sed -i '/var apnsPrivateKey = `/,/`/d' apns/apns_certs.go
          echo "var apnsPrivateKey = \`" >> apns/apns_certs.go
          echo "${{ secrets.P8_KEY }}" >> apns/apns_certs.go
          echo "\`" >> apns/apns_certs.go

      - name: Build and Export Docker
        run: |
          docker build -t private-bark:latest -f ./deploy/Dockerfile .
          docker save private-bark:latest > bark-server.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bark-server-image
          path: bark-server.tar
          retention-days: 1
